# Generated by Django 3.0 on 2020-01-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reponseQuestion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.CreateModel(
            name='FaireSujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEtu', models.ForeignKey(db_column='numEtu', on_delete=django.db.models.deletion.CASCADE, to='toeic.Etudiant')),
                ('numSujet', models.ForeignKey(db_column='numSujet', on_delete=django.db.models.deletion.CASCADE, to='toeic.Sujet')),
            ],
            options={
                'db_table': 'fairesujet',
            },
        ),
    ]
