# Generated by Django 3.0 on 2019-12-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toeic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailProf', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'prof',
            },
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='classeEtudiant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nomEtudiant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='numEtudiant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenomEtudiant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='classeEtu',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mailEtu',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='numEtu',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
