# Generated by Django 3.0 on 2019-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0002_auto_20191222_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetEtu',
            fields=[
                ('numSujet', models.AutoField(primary_key=True, serialize=False)),
                ('nomSujet', models.CharField(blank=True, max_length=20)),
                ('mdpSujet', models.CharField(blank=True, max_length=20)),
                ('Q1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Q2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Q3', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Q4', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Q5', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
            ],
            options={
                'db_table': 'sujet_Etu',
            },
        ),
    ]
