# Generated by Django 2.2.1 on 2020-01-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0002_auto_20200103_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numClasse', models.ForeignKey(db_column='numClasse', on_delete=django.db.models.deletion.CASCADE, to='toeic.Classe')),
                ('numProf', models.ForeignKey(db_column='numProf', on_delete=django.db.models.deletion.CASCADE, to='toeic.Professeur')),
            ],
            options={
                'db_table': 'enseigner',
            },
        ),
    ]
