# Generated by Django 3.0 on 2020-01-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0003_enseigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corriger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSujetEtu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numSujetEtu', to='toeic.Sujet')),
                ('numSujetProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numSujetProf', to='toeic.Sujet')),
            ],
            options={
                'db_table': 'corriger',
            },
        ),
    ]
