# Generated by Django 3.0 on 2020-01-15 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0004_corriger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='noteSujet',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(990)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponseQuestion',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.DeleteModel(
            name='Correspondre',
        ),
        migrations.DeleteModel(
            name='SessionToeic',
        ),
    ]
